// metro-map.js — interactive map: the OFFICIAL plano image plus an
// invisible hotspot button per modelled station. Positions come from
// metro-map-data.js (generated by tools/extract-metro-map.mjs via OCR of
// the plano PDF + manual overrides), expressed as image fractions so the
// hotspots track the image at any size.

import { mapImage, stationPositions } from '../data/metro-map-data.js';
import { allStations } from '../data/metro.js';
import { t } from '../../../i18n/index.js';

// padding around each label anchor, as image fractions — covers the station
// tick next to the label too
const PAD_X = 0.018;
const PAD_Y = 0.016;
const MIN_W = 0.035;
const MIN_H = 0.026;

export function renderMetroMap({ selected = null } = {}) {
  const buttons = allStations()
    .map((name) => {
      const p = stationPositions[name];
      if (!p) return '';
      const fw = Math.max(p.w + PAD_X * 2, MIN_W);
      const fh = Math.max(p.h + PAD_Y * 2, MIN_H);
      return `<button type="button" class="metro-station${
        selected === name ? ' selected' : ''
      }" data-station="${name}" aria-label="${name}" style="left:${(
        (p.x - fw / 2) * 100
      ).toFixed(3)}%;top:${((p.y - fh / 2) * 100).toFixed(3)}%;width:${(fw * 100).toFixed(
        3
      )}%;height:${(fh * 100).toFixed(3)}%"></button>`;
    })
    .join('');

  return `<div class="metro-map" role="group" aria-label="${t('metro.mapAlt')}"
      style="aspect-ratio: ${mapImage.w} / ${mapImage.h}">
    <img src="/metro/metro-map.png" alt="" />
    ${buttons}
  </div>`;
}
